### ISSUE TITLE
add a cronjob to mina-archive to backup postgresql to s3

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#51]
### Problem

We need to back up archive on a daily basis so we would be able to restore it when needed. Or provide others a source of blockchain history. 

### Acceptance Criteria

we are able to create helm charts that allow to enable backups to s3 as a cronjob and successfully run it once a day

### Tasks

- [x] user is able to toggle a backup option. 
- [x] there is a bucket on s3 that helm chart is able to post backups to
- [x] changes reflect in documentation/README
