### ISSUE TITLE
Log current and next staking ledgers in cron

### ISSUE THREAD

**Issue by trevorbernard** [MinaFoundation/helm-charts#54]
### Problem

Manual intervention is required to maintain the list of exported epoch staking ledgers for a given Mina network. Here is an example of a helm cron in the Mina codebase: https://github.com/MinaProtocol/mina/blob/compatible/helm/cron_jobs/mainnet-dump-staking-ledger-cronjob.yaml

### Acceptance Criteria

The cron should run in the middle of a epoch so it can export the current and next staking ledger. The interval should be the time in minutes for a 7140 slot epoch. To be safe, you can run it in half the time so you guarantee that at least one export will contain both.

### Tasks

- [ ] Create helm cron file for dumping staking ledgers
- [ ] Ensure cron interval is 7140 slot minutes or smaller
- [ ] Provision s3 buckets to accept ledger dumps
- [ ] Modify cronjob.yml to pushing to said s3 bucket
- [ ] Update documentation/README

**Comment by Killpit** [comment]
Is this still a relevant issue?

**Comment by kaozenn** [comment]
Completed as part of https://github.com/MinaFoundation/helm-charts/tree/main/mina-staking-ledgers-exporter
