### ISSUE TITLE
cronjob to store produced blocks in S3 as json

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#55]
**Problem**

Create a job that syncs block state hashes to S3.

**Acceptance Criteria**

A deployed mina-archive helm chart includes a job that is constantly making sure that all block state hashes are stored as json files in S3. 

**Tasks**

- [x] Documentation/Readme to reflect the changes
- [x] make sure state hashes are available locally on disk
- [x] make sure that they are synced with s3

**Comment by kaozenn** [comment]
Should we move this issue to the Jira Board?

**Comment by simisimis** [comment]
We should have an equivalent task on jira, just not sure what do we do  with gh issues.close them or link them

**Comment by kaozenn** [comment]
I found it was easier to create a new Jura issue and copy/paste the content
of the GH issue
