### ISSUE TITLE
Store precomputed blocks on PVC

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#60]
### Problem

There are cases when we would want to store precomputed blocks locally (in k8s Persisten Volume). 

### Acceptance Criteria

When this is implemented, by setting storeBlocks to true, helm chart would create a Persistent Volume Claim and configure mina daemon to start with `--precomputed-blocks-file` 

### Tasks

- [x] Documentation/Readme
- [x] PVC resource template added
- [x] deployment template updated
- [x] values.yaml updated
