### ISSUE TITLE
implement snark coordinator mode for mina-daemon helm chart

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#62]
### Problem

We need to be able using `mina-daemon` helm chart to start SNARK coordinator.

### Acceptance Criteria

Setting in values.yaml `coordinator` mode, would start mina daemon with SNARK coordinator enabled. 

### Tasks

- [x] Update README/Documentation
- [x] feature added to template
- [x] vars added to values.yaml
