### ISSUE TITLE
add labels to scraped metrics for mina-daemon and mina-archive

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#64]
### Problem

when creating grafana dashboards, we need to be able to select resources by testnet they are in, or by role they are performing(i.e. `mina-daemon` can be running as seed node of BP or SW etc.)
Therefore as we are scraping metrics endpoints we also need to enrich those metrics with those labels.

### Acceptance Criteria

Once this is merged, resources we will provision with these helm charts will have services exposing metrics endpoint running with labels: `testnet`, `class`. And `service-monitor` kubernetes resource will be adding them to the scraped metrics.

### Tasks

- [x] Update README/Documentation
- [x] Adjust service template in archive and daemon helm charts.
- [x] Adjust service-monitor template in archive and daemon helm charts.
