### ISSUE TITLE
add resource allocation limits to mina-daemon and mina-archive 

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/helm-charts#66]
### Problem

Some of the metrics are only reported when `resources.requests` and `resources.limits` are set. Therefore we cannot create some of graphs in our monitoring dashboards.

### Acceptance Criteria

Extend helm charts to have `resources.requests` and `resources.limits` values that could be configured and have sensible defaults. Make sure that metrics like: 
- `container_cpu_cfs_throttled_seconds_total`
- `container_cpu_usage_seconds_total`
- `kube_pod_container_resource_requests`
report data.

### Tasks

- [x] Update Readme/Documentation
- [x] Update deployments template for mina-daemon, mina-archive charts
- [x] Update values.yaml
